### ISSUE TITLE
Database Password

### ISSUE THREAD

**Issue by rimoore** [jbfavre/docker-vertica#12]
Is there a variable I can set so the db has a password?

**Comment by jbfavre** [comment]
Hi @rimoore 
No, there're currently no variable you could use to set a DB password

**Comment by rimoore** [comment]
Thanks, I'd appreciate this enhancement as my source application has field validation that prevents me from saving a blank password.

**Comment by jbfavre** [comment]
@rimoore I have no plan to implement it in a near future.
That said, you're are welcome to contribute with a pull request

**Comment by rimoore** [comment]
> @rimoore I have no plan to implement it in a near future.
> That said, you're are welcome to contribute with a pull request

Wish I knew how :). I do appreciate having this image to use in my testing. Thanks for all the hard work.

**Comment by jbfavre** [comment]
Fixed with latest version of the image. Please have a look on README file for deta
Thanks for reporting the issue !
