### ISSUE TITLE
Short wait time for start

### ISSUE THREAD

**Issue by uzhao** [jbfavre/docker-vertica#7]
I create a database with persistent data store. It has a catalog over 1g. When I start the container, I got this error msg. Can I change somewhere to make it wait a little bit longer or this could be something else? Thanks!

Starting up
Fixing filesystem permissions
Starting Database
Info: no password specified, using none
        Starting nodes: 
                v_docker_node0001 (127.0.0.1)
        Starting Vertica on all nodes. Please wait, databases with a large catalog may take a while to initialize.
        Node Status: v_docker_node0001: (DOWN) 
        Node Status: v_docker_node0001: (DOWN) 
        Node Status: v_docker_node0001: (DOWN) 
        Node Status: v_docker_node0001: (INITIALIZING) 
        Node Status: v_docker_node0001: (DOWN) 
        Node Status: v_docker_node0001: (DOWN) 
        Node Status: v_docker_node0001: (DOWN) 
        Node Status: v_docker_node0001: (DOWN) 
        Node Status: v_docker_node0001: (DOWN) 
        Node Status: v_docker_node0001: (DOWN) 
        Database startup not yet successful --- no nodes report up.
        Waiting can sometimes resolve this problem, especially on databases
        with large catalogs.  See Database Cluster State in Main Menu for updated
        cluster state.
Database docker did not start successfully: Nodes Failed to come up

**Comment by jbfavre** [comment]
Hello @uzhao 
Almost a year to answer you, please accept my deepest apologies.
Could you please test the fix in https://github.com/jbfavre/docker-vertica/commit/f6d715b0efddde77833bed1540a63fb7a2565c35 ?

Cheers,
